services:
  - type: web
    name: fuelmate-web
    runtime: docker
    plan: free
    region: singapore
    autoDeployTrigger: commit
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: FuelMate
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: fuelmate-db
          property: connectionString
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: BROADCAST_CONNECTION
        value: log
      - key: MAIL_MAILER
        value: log
      - key: RUN_SCHEDULER
        value: "true"

databases:
  - name: fuelmate-db
    plan: free
    region: singapore
